// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB68e_n6wh9qRD1ljQ6r2S1dMGV92bcO8E',
    appId: '1:451449929420:web:9f0c678a8e5a8f70420c69',
    messagingSenderId: '451449929420',
    projectId: 'flutternewprojects-68879',
    authDomain: 'flutternewprojects-68879.firebaseapp.com',
    databaseURL: 'https://flutternewprojects-68879-default-rtdb.firebaseio.com',
    storageBucket: 'flutternewprojects-68879.firebasestorage.app',
    measurementId: 'G-8B8P4G0FQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQHLwSCmhCMMHiY_cI0oa_UchvCvCTpSE',
    appId: '1:451449929420:android:45532cd256a24cce420c69',
    messagingSenderId: '451449929420',
    projectId: 'flutternewprojects-68879',
    databaseURL: 'https://flutternewprojects-68879-default-rtdb.firebaseio.com',
    storageBucket: 'flutternewprojects-68879.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBDuzYSOR6IiROFNmjVC0nKn6NO2Dql8A',
    appId: '1:451449929420:ios:977eec04e45e3653420c69',
    messagingSenderId: '451449929420',
    projectId: 'flutternewprojects-68879',
    databaseURL: 'https://flutternewprojects-68879-default-rtdb.firebaseio.com',
    storageBucket: 'flutternewprojects-68879.firebasestorage.app',
    androidClientId: '451449929420-0g9as4e4v5d5cinb3b771kgo63c5ktns.apps.googleusercontent.com',
    iosClientId: '451449929420-ejcvq2unpk80ifcatek9en4lpsg99557.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattingNewApp',
  );
}
